<div id="focus_bg">

</div>
<div id="wrapper"> <!-- Wraps whole page content -->
<div id="left">

<?php include ("inc.nav.php"); ?>



<div id="knowledge_contents">
<p>Contents</p>
<ol>
<li><a href="#overview" >1 Overview</a></li>
<li><a href="#uses" >2 Uses</a>
	<ol class="internal">
	<li><a href="#electricity" >2.1 Electricity</a></li>
	<li><a href="#naval" >2.2 Naval Propulsion</a></li>
	<li><a href="#space" >2.3 In Space</a></li>
	</ol></li>
<li><a href="#producers" >3 Largest Producers</a>
	<ol class="internal">
	<li><a href="#kwh" >3.1 Countries by kWh</a></li>
	<li><a href="#overall" >3.2 Countries by Overall</a></li>
	</ol>
</li>
<li><a href="#history" >4 History</a></li>
<li><a href="#technology" >5 Technology</a>
	<ol class="internal">
	<li><a href="#pressurized" >5.1 Pressurized Reactors</a></li>
	<li><a href="#boiling" >5.2 Boiling Water Reactors</a></li>
	<li><a href="#fission" >5.3 Fission & Fusion</a></li>
	</ol>
</li>
<li><a href="#economics" >6 Economics</a></li>
<li><a href="#table" >7 Nuclear Power by Country</a></li>
<li><a href="#effect" >8 Effect on the Climate</a>
	<ol class="internal">
		<li><a href="#renewable" >8.2 Is It Renewable?</a></li>
		<li><a href="#safety" >8.3 Safety Concerns</a></li>
	</ol>
</li>
<li><a href="#references" >9 References</a></li>
</ol>












</div>

<div id="suggest_change">
<a href="" >Suggest a change</a>
</div>
</div>

<div id="focus_bar">
<h1 id="focus_title">Knowledge: <?php echo ("$page_title"); ?></h1>
<a href="" id="focus_action" >Discuss this &rarr;</a>
<a href="" id="focus_feedback" >Feedback &#43;</a>
<a href="" id="focus_all" >All Articles<img src="css/images/arrow_down.png" alt="" ></a>



</div>
<div id="middle">
<!-- Temporary info for visual purposes -->
<div id="knowledge_article">
<h2>Overview</h2>
<p>Nuclear power is created through controlled nuclear reactions that release heat, which is then used to boil water, releasing steam that used to spin a turbine. As the turbine spins its generator turns and the magnetic field changes, creating electricity. All nuclear reactors today utilize nuclear fission, or the breaking apart of a uranium nuclei to release energy; nuclear physicists hope to some day harness the power of nuclear fusion, or the fusion of two nuclei, to generate energy on a much more massive scale. Interest has recently increased in nuclear energy as an alternative source of energy as global warming concerns take center stage around the world.</p>
<h2>Nuclear Energy Uses</h2>
<p>Nuclear energy's biggest use is as electricity generated by power plants, but it has also found a niche in the propulsion systems of naval vessels and in equipment used in space.</p>
<h3>Electricity</h3>
<p>Industrialized nations like the U.S., U.K., Germany, France, and Japan account for most of the electricity produced by nuclear power plants, but developing countries like China and South Africa have been constructing new facilities; currently 31 nations produce their own nuclear power (link to countries section). Further below is a table listing all nuclear power-producing nations (and ones planning to do so), as well as the number of reactors they operate and the percentage of their energy that comes from nuclear power.</p>
<h3>Naval Propulsion</h3>
<p>According to the World Nuclear Association, greater than 180 small nuclear reactors generate energy for around 140 ships, most which are submarines but include other types - from icebreakers and aircraft carriers. This type of power source is best suited for ships that have to be away from port for prolonged periods of time, and becomes more practical as fossil fuel sources become more limited. It has also proven particularly useful on icebreakers in the Russian arctic, where large amounts of energy are needed to break the unusually thick ice and refueling is difficult. Nuclear propulsion systems use highly-enriched uranium to produce large amounts of energy while taking up relatively small amounts of space, and refueling is only needed after 10-50 years depending on how new the design of the core is.
In 2009 China’s COSCO, the world's largest shipping conglomerate, expressed interest in putting nuclear propulsion systems on merchant ships in order to reduce the emissions that commercial shipping currently releases.</p>
<h3>Nuclear Power in Space</h3>
<p>Unmanned space vehicles also rely on nuclear power for their energy, though not through fission reactions. Instead they utilize radioisotope thermoelectric generators (RTGs) to generate power that is used for running their computers. Most RTGs produce around 300 watts of electricity and can do so for many years, demonstrated by the scacecraft Voyager1 and Voyager 2 that were launched more than 30 years ago but are still operational billions of miles from the sun.</p>
<p>Not all space missions depend on this power source, but many do. Two of the most well-known missions that have utilized RTG power are the Galileo mission and the New Horizons mission, which were intended to study Jupiter and Pluto, respectively. The Galileo spacecraft mission orbited Jupiter 35 times during a 2-year timespan, and scientists used the data it collected in an effort to better understand the Earth's atmosphere and climate change. The New Horizons spacecraft mission was the latest NASA mission, and is in transit to Pluto at this moment. [4]</p>
<h2>Largest Nuclear Energy Producers</h2>
<p>Industrialized nations are traditionally the largest producers of nuclear energy because of the high initial capital investment involved, but developing nations have been planning increasingly more plants as their energy needs rapidly grow. In the United States the majority of nuclear power plants are in the eastern half of the country, with the greatest concentration in the east coast states, and no new nuclear plants have been constructed in the U.S. since 1996.</p>
<p>The largest producers by billions of kWh as of February 2011 are:</p>
<ol>
<li>United States - 798.7</li>
<li>France - 391.7</li>
<li>Japan - 263.1</li>
<li>Russia - 152.8</li>
<li>South Korea - 141.1</li>
<li>Germany - 127.7</li>
<li>Canada - 85.3</li>
<li>Ukraine - 77.9</li>
<li>China - 65.7</li>
<li>United Kingdom - 62.9</li>
</ol>

<p>The largest producers by percentage of overall electricity production as of February 2011 are:</p>
<ol>
<li>Lithuania - 76.2&#37;</li>
<li>France - 75.2&#37;</li>
<li>Slovakia - 53.5&#37;</li>
<li>Belgium - 51.7&#37;</li>
<li>Ukraine - 48.6&#37;</li>
<li>Switzerland - 39.5&#37;</li>
<li>Slovenia - 37.9&#37;</li>
<li>Bulgaria - 35.9&#37;</li>
<li>South Korea - 34.8&#37;</li>
<li>Sweden - 34.7&#37;</li>
</ol>
<p>Source: See table of nuclear power by country below</p>

<h2>History of Nuclear Energy</h2>
<p>Nuclear research initially began during World War II as focused mainly on creating nuclear weapons to quickly end a war that was shaking the foundation of our civilizations, but afterwards scientists turned towards using their new-found source of power for peaceful means. Since then a wide array of industries and fields have found uses for nuclear power, from medical to industrial applications.</p>
<p>Ancient Greek philosophers were the first to develop the concepts that underlay nuclear reactions: that all matter consists of tiny building blocks called atoms, and by 1900 physicists had ascertained that these little atoms contained incredible amounts of energy. In 1904 the father of nuclear science, Ernest Rutherford, wrote that “If it were ever possible to control at will the rate of disintegration of the radio elements, and enormous amount of energy could be obtained from a small amount of matter.” Shortly thereafter, Albert Einstein came out with his famous equation: E=mc2, which defines the relationship between energy, mass, and the speed of light.</p>
<p>In the early-mid 1900's the scientists Enrico Fermi, Otto Hahn, Fritz Strassman, and Lise Meitner were all involved in various experiments in splitting many kinds of atoms. Eventually Lise Meitner realized that the masses of the light elements left over from splitting a uranium atom did not equal the mass of the uranium atom, and used Einsteins theory to demonstrate that the lost mass had turned into energy, thus proving Einstein’s work.</p>
<p>On December 2, 1942, Enrico Fermi led a group of scientists in creating the first self-sustaining chain reaction beneath the University of Chicago’s athletic stadium, thus ushering in the nuclear age. From this point forward most work regarding nuclear power was under the umbrella of the Manhattan Project, the aim of which was to develop a weapon to be used in World War II. After the war ended though, the United States government encouraged the development of nuclear energy for peaceful uses, and the first energy generated by nuclear reactor was created on December 20, 1951 in Idaho.</p>
<p>Around this time the major goal was to prove that nuclear power could be commercially viable for large-scale energy production, and the first commercial power plant was located in Shippingport, Pennsylvania. During the 1960s the nuclear power industry grew rapidly, but during the 1970s and 1980s growth slowed as safety issues and environmental concerns increased. However, by 1991 the United States had one-fourth of the world’s operating nuclear power plants, double any other country, and produced 22 percent of its energy using it.</p>
<p>Nuclear power plant construction stalled at this point in the U.S., with the last reactor being built in 1996. Other countries, like France and Japan, have continued to push forward. The recent economic trend of globalization has seen a resurgence of interest in nuclear power among developing nations, with China leading the way. If China builds all 160 of the nuclear power plants it has planned or proposed it will have more than any other nation, including the United States. Industrialized countries too have seen a recent resurgence of interest in nuclear energy as concerns of global warming push societies to adopt sources of energy with less greenhouse gas emission.</p>

<h2>Technology Behind Nuclear Energy</h2>
<p>A nuclear power plant harnesses the energy from nuclear reactions then uses it to heat water into pressurized steam, and uses this steam to drive a turbine generator that produces electricity. This is the same way most power plants work, in that they use varying fuel sources to create steam and generate electricity. At present, nuclear plants rely on breaking apart a uranium atom using a process called nuclear fission. The opposite, combining two atoms, is called fusion and has been heavily researched for decades because of its greater potential for generating energy. However, no controllable option for this type of reaction has yet been found. The steam that is produced by the nuclear reactor is cooled back into water after the process so that it can be reused. The buildings in which the reactions take place are the containment buildings, and have concrete walls 3 to 6 feet thick to contain any rogue radioactivity [2].</p>
<p>The Uranium fuel that is used is kept in small ceramic pellets about the size of an adult’s fingertip, which are stacked in a row along 12-foot metal fuel rods called fuel assemblies. Each of these ceramic pellets contains the energy equivalent of about 150 gallons of oil [3].</p>

<h3>Pressurized Reactors</h3>
<p>These reactors use two sources of water for steam production – one that becomes irradiated and one from clean sources like lakes and rivers. The source that is reused within the facility is heated up by the nuclear reactions but kept from boiling, and thus stays liquid. It then flows through a second piece of equipment called a steam generator, which itself is heated up, and in turn boils the second source of water to produce steam. The irradiated water is recycled back to the reactor where the process is repeated.</p>

<h3>Boiling Water Reactors</h3>
<p>In these types of facilities the water is simply boiled, and thus turned into steam that turns the turbine generators.</p>

<h3>Nuclear Fission</h3>
<p>There is a huge amount of energy stored in the bonds of an atom, which fission breaks apart in order to harness. During this process an extremely small particle called a neutron is fired at a uranium atom, breaking it apart and releasing heat and radiation in the process. More neutrons are released from the split uranium atom, which go on to hit other uranium atoms, resulting in a chain reaction.</p>

<h3>Nuclear Fusion</h3>
<p>Nuclear fusion produces energy as a byproduct of combining two atoms, and is the primary way in which our sun creates its energy.</p>


<h2>Economics of Nuclear Energy</h2>
<p>Primary factors in the economics of nuclear power include: the demand/supply of uranium, the cost of other types of fuel, the initial capital investment in a nuclear power plant, and political or social influences on energy production - like safety and environmental concerns.</p>
<p>First and most evidently, as the cost of oil per barrel increases the attractiveness of nuclear energy, as well as most other alternative energy sources, also increases.</p>
<p>The demand for uranium is expected to greatly outstrip the supply of it over the next 10 years as the developing world’s nuclear power plants start to operate. Countries like China and India have been investing large amounts in their nuclear energy industries, while the mining of uranium is not expected to match this growth rate.</p>
<p>Interest in nuclear energy has been revived lately as anthropogenic climate change has become more accepted by the world. Increased fears of global warming lead to greater interest in non-carbon-based energy sources, such as nuclear energy. National commitments to highly energy-efficient and low greenhouse-gas-emitting sources of energy to stem the tide of global warming will likely result in increasingly more nuclear energy capital investment over the coming decade. As corporations are increasingly face their contribution to global warming they are also likely to turn to alternative energy sources like nuclear energy, thus further increasing its demand.</p>
<p>The events that could most seriously impact the nuclear energy markets are a nuclear accident in one of the world nuclear power plants, an explosion of a nuclear device or nuclear plant sabotage by terrorist groups, or the world’s inability to address both non-proliferation goals and nuclear energy advancement.</p>

<h2>Nuclear Energy Generation by Country</h2>
<table summary="nuclear energy production capacity and power plant construction of world countries" >
<tr class="TRh">
<td>Country</td>
<td>Nuclear Energy Electricity Generation in kWh</td>
<td>Nuclear Energy Generation as &#37; of total electricity generation</td>
<td>Reactors Operable</td>
<td>Reactors Under Construction</td>
<td>Reactors Proposed or Planned</td>
</tr>
<tr class="TRo">
<td>Argentina</td>
<td>7.6</td>
<td>7.0</td>
<td>2</td>
<td>1</td>
<td>3</td>
</tr>
<tr class="TRe">
<td>Armenia</td>
<td>2.3</td>
<td>45</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="TRo">
<td>Bangladesh</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="TRe">
<td>Belarus</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="TRo">
<td>Belgium</td>
<td>45</td>
<td>51.7</td>
<td>7</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="TRe">
<td>Brazil</td>
<td>12.2</td>
<td>3</td>
<td>2</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="TRo">
<td>Bulgaria</td>
<td>14.2</td>
<td>35.9</td>
<td>2</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="TRe">
<td>Canada</td>
<td>85.3</td>
<td>14.8</td>
<td>18</td>
<td>2</td>
<td>6</td>
</tr>
<tr class="TRo">
<td>China</td>
<td>65.7</td>
<td>1.9</td>
<td>13</td>
<td>27</td>
<td>160</td>
</tr>
<tr class="TRe">
<td>Czech Republic</td>
<td>25.7</td>
<td>33.8</td>
<td>6</td>
<td>0</td>
<td>3</td>
</tr>
<tr class="TRo">
<td>Egypt</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="TRe">
<td>Finland</td>
<td>22.6</td>
<td>32.9</td>
<td>4</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="TRo">
<td>France</td>
<td>391.7</td>
<td>75.2</td>
<td>58</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="TRe">
<td>Germany</td>
<td>127.7</td>
<td>26.1</td>
<td>17</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="TRo">
<td>Hungary</td>
<td>14.3</td>
<td>43</td>
<td>4</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="TRe">
<td>India</td>
<td>14.8</td>
<td>2.2</td>
<td>20</td>
<td>5</td>
<td>58</td>
</tr>
<tr class="TRo">
<td>Indonesia</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>6</td>
</tr>
<tr class="TRe">
<td>Iran</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>3</td>
</tr>
<tr class="TRo">
<td>Israel</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="TRe">
<td>Italy</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>10</td>
</tr>
<tr class="TRo">
<td>Japan</td>
<td>263.1</td>
<td>28.9</td>
<td>55</td>
<td>2</td>
<td>13</td>
</tr>
<tr class="TRe">
<td>Jordan</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="TRo">
<td>Kazakhstan</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>4</td>
</tr>
<tr class="TRe">
<td>North Korea</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="TRo">
<td>South Korea</td>
<td>141.1</td>
<td>34.8</td>
<td>21</td>
<td>5</td>
<td>6</td>
</tr>
<tr class="TRe">
<td>Lithuania</td>
<td>10.0</td>
<td>76.2</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="TRo">
<td>Malaysia</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="TRe">
<td>Mexico</td>
<td>10.1</td>
<td>4.8</td>
<td>2</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="TRo">
<td>Netherlands</td>
<td>4</td>
<td>3.7</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="TRe">
<td>Pakistan</td>
<td>2.6</td>
<td>2.7</td>
<td>2</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="TRo">
<td>Poland</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>6</td>
</tr>
<tr class="TRe">
<td>Romania</td>
<td>10.8</td>
<td>20.6</td>
<td>2</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="TRo">
<td>Russia</td>
<td>152.8</td>
<td>17.8</td>
<td>32</td>
<td>10</td>
<td>44</td>
</tr>
<tr class="TRe">
<td>Slovakia</td>
<td>13.1</td>
<td>53.5</td>
<td>4</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="TRo">
<td>South Africa</td>
<td>11.6</td>
<td>4.8</td>
<td>2</td>
<td>0</td>
<td>6</td>
</tr>
<tr class="TRe">
<td>Spain</td>
<td>50.6</td>
<td>17.5</td>
<td>8</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="TRo">
<td>Sweden</td>
<td>50.0</td>
<td>34.7</td>
<td>10</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="TRe">
<td>Switzerland</td>
<td>26.3</td>
<td>39.5</td>
<td>5</td>
<td>0</td>
<td>3</td>
</tr>
<tr class="TRo">
<td>Thailand</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="TRe">
<td>Turkey</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>8</td>
</tr>
<tr class="TRo">
<td>Ukraine</td>
<td>77.9</td>
<td>48.6</td>
<td>15</td>
<td>0</td>
<td>22</td>
</tr>
<tr class="TRe">
<td>UAE</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>14</td>
</tr>
<tr class="TRo">
<td>United Kingdom</td>
<td>62.9</td>
<td>17.9</td>
<td>19</td>
<td>0</td>
<td>13</td>
</tr>
<tr class="TRe">
<td>USA</td>
<td>798.7</td>
<td>20.2</td>
<td>104</td>
<td>1</td>
<td>32</td>
</tr>
<tr class="TRo">
<td>Vietnam</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>14</td>
</tr>
</table>
<p>Note: A typical 1,000 megawatt-electric (MWe) reactor can provide enough electricity for a city of about 600,000 people.</p>
<p>This data was retrieved from the World Nuclear Association at their information page on reactors on February 15, 2011. Their reports are updated every two months or as needed.</p>

<h2>Effect on the Climate & Environment</h2>
<p>Nuclear energy power plants themselves do not directly emit the type of fossil fuel emissions related to anthropogenic climate change like carbon dioxide, nitrogen oxides, or sulfur dioxide. In the holistic nuclear energy production process though, the current techniques used to mine, enrich, and transport uranium (the fuel behind nuclear energy) do have associated emission costs that impact our atmosphere and may contribute to global warming.</p>
<p>It does however fare better than biofuels, wind farms, or photovoltaics in term of the amount of space the process requires, as a nuclear power plant occupies relatively small tracts of land. However, storage of nuclear waste is a pressing issue that no clear answer exists for; currently, most nuclear waste is stored at the production facility in thick concrete storage facilities.</p>

<h3>Is Nuclear Energy Renewable?</h3>
<p>Nuclear energy produced through fission is not renewable, as it uses uranium as fuel. Uranium is a relatively rare metal found in rocks all around the Earth, while it is about 100 times more common than silver [3], it is still of a limited supply. Most is mined in the United States, and the specific type of Uranium used in nuclear fission, U-235, must be extracted before use.</p>

<h3>Nuclear Energy Safety Concerns</h3>
<p>The Nuclear Regulatory Commission (NRC) regulates the U.S. Nuclear Power industry, and strives to ensure the safety of those who work in or live near nuclear power plants.</p>
<p>The most commonly cited threats that nuclear power plants pose to the populace are in the risk of a plant becoming unstable, like the 3 mile island or Chernobyl incidents, and in the cumulative effect of nuclear waste. The harm of merely living near a nuclear power plant is negligible, as the amount of radiation one will absorb due to their proximity to the nuclear material is less than one diagnostic X-ray procedure. Modern nuclear energy production facilities are equipped with sophisticated automatic safety features, which are designed to shut down the power plant before its safety margins are exceeded. The industry refers to unplanned automatic shut downs of this nature as “scrams” or “trips”.</p>
<p>The high-level nuclear waste of a production facility consists of the spent fuel used in the nuclear reactor, and can retain its radioactivity for thousands of years. Currently most nuclear waste is stored either in on-site locations or special external storage facilities. The U.S. Department of Energy has proposed development of a permanent waste disposal site at Mt. Yucca, Nevada, where waste could be stored for thousands of years.</p>
<p>All nuclear power plants are equipped with heavily armed security forces to keep intruders out. On a national level, proponents of nuclear energy point to it as being key to national security for any country. It is relatively unaffected by variable weather, unpredictable cost fluctuations, or foreign suppliers. However this last point is questionable, as in 2008 only 14% of Uranium delivered to U.S. nuclear power plants was mined in the U.S., while the rest was from foreign countries. Australia and Canada supplied 42%, Uzbekistan, Russia, and Kazakhstan provided 33%, and the United Kingdom, Czech Republic, South Africa, Namibia, Niger, and Brazil delivered 11%. [3]</p>





</div>
</div>
<div id="right">
<div id="social" class="right_section">
<a href="" id="social_fb" ><img src="css/images/button_fb.png" alt="" ></a>
<a href="" id="social_google" ><img src="css/images/button_google.png" alt="" ></a>
<a href="" id="social_twitter" ><img src="css/images/button_twitter.png" alt="" ></a>

</div>
<div id="intro" class="right_section">
<h3 class="right_header">Shout it out!</h3>
<p id="intro_about">Climatepedia.org is a university student-run program providing a modern and balanced connection point between researchers and the public about climate change.</p>

<p><a href="" >FAQ &#187;</a> | <a href="" >About &#187;</a></p>
</div>
<div id="knowledge_images" class="right_section">
<h3 class="right_header"><?php echo("$page_title"); ?> images</h3>
<a href=""><img src="knowledge-base/images/nuclear_energy_plant.jpg" width="160px" alt="" ></a>
<a href=""><img src="knowledge-base/images/nuclear_energy_submarine.jpg" width="160px" alt="" ></a>
<a href=""><img src="knowledge-base/images/nuclear_energy_tower.jpg" width="160px" alt="" ></a>
<a href=""><img src="knowledge-base/images/nuclear_energy_waste.jpg" width="160px" alt="" ></a>
</div>
<div id="suggestions" class="right_section">
<h3 class="right_header">Suggested for you</h3>
</div>
<div id="popular" class="right_section">
<h3 class="right_header">Most popular</h3>
</div>
<div id="recent" class="right_section">
<h3 class="right_header">Recent activity</h3>
</div>




</div>
</div>
